# TODO: Change the name of the org 
org: vianneykb01
app: serverless-todo-5
service: serverless-todo-5
FrameworkVersion: '3.23.0'

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

#  X-Ray Tracing
  tracing:
    lambda: true
    apiGateway: true

  environment:
    PROJECT_NAME: serverlessapp-5
    TODOS_TABLE: Todos-dev-5-${self:provider.stage}
    S3_BUCKET_NAME: s3-vianney-sls-dev-5-${self:provider.stage}

    TODOS_CREATED_AT_INDEX: CreatedAtIndex
    INDEX_NAME: ${self:provider.environment.TODOS_CREATED_AT_INDEX}
    SIGNED_URL_EXPIRATION: 300
    AUTH_0_SECRET_ID: --9eAfv9W_X2sNgm-YgdZyCBZ0EeW8RIgUYe2uXCTbEwhqYjJ5VOznCGjD5vLvsE

custom:
  documentation:
    api:
      info:
        version: '1.0.0'
        title: serverless-api
        description: serverless-api
    models:
      - name: CreateTodoRequest
        contentType: "application/json"
        schema:
          required:
            - name
            - dueDate
          properties:
            name:
              minLength: 1
              type: string
            dueDate:
              type: string
      - name: UpdateTodoRequest
        contentType: "application/json"
        schema:
          required:
            - name
            - dueDate
            - done
          properties:
            name:
              minLength: 1
              type: string
            dueDate:
              type: string
            done:
              type: boolean    

functions:

  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

